#pragma once

#define PERSIST_TMP_TEMPERATURE  0
#define PERSIST_TMP_LAST_BOTTOM  1
#define PERSIST_CFG_BACKGROUND_1 2
#define PERSIST_CFG_BACKGROUND_2 3
#define PERSIST_CFG_BACKGROUND_3 4
#define PERSIST_CFG_SHOW_TEMP    5
#define PERSIST_CFG_SHOW_DATE    6
#define PERSIST_CFG_DATE_FORMAT  7
#define PERSIST_CFG_SHOW_STEPS   8
#define PERSIST_CFG_STEP_GOAL    9
#define PERSIST_CFG_BOTTOM_DISP  10
#define PERSIST_CFG_QUICK_VIEW   11
#define PERSIST_CFG_BG_CYCLE_INT 12
#define PERSIST_TMP_UPDATE_BG_TIME  13
#define PERSIST_TMP_CURRENT_BG   14

#define CONFIG_DATE_MMDD  0
#define CONFIG_DATE_DDMM  1

#define CONFIG_BOTTOM_NONE     0
#define CONFIG_BOTTOM_WEATHER  1

#define CONFIG_QV_ACTION_NOTHING  0
#define CONFIG_QV_ACTION_ROLLUP   1